# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Delabuild'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left nice_view_adapter nice_view", "corne_right nice_view_adapter nice_view"]'
      branches: '["caksoylar/zmk/feat/mouse-keys-3.2"]'
      kconfig: '["CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=16\nCONFIG_BT_CTLR_TX_PWR_PLUS_8=y\nCONFIG_ZMK_DISPLAY=y"]'
